# Generated by Django 4.0 on 2025-11-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='external_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
