# Generated by Django 5.2.8 on 2025-11-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_external_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/default_user.png', null=True, upload_to='profiles/'),
        ),
    ]
