# Generated by Django 5.2.8 on 2025-11-25 03:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_portfolios', through='Portfolio.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
